## Numpy

- Provides n-dimensional arrays (ndarray) or numpy.array
- Dimensions = axes
- Number of axes = rank
- Unlike normal arrays most methods change things in place

In [5]:
import numpy as np

a = np.arange(15).reshape(3,5)
print(a)
print('Dimensions of the array -', a.shape)
print('Data type in the array -', a.dtype)
print('Total items in array -', a.size)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Dimensions of the array - (3, 5)
Data type in the array - int32
Total items in array - 15


### Creation

- Can Create from lists or tuples

In [6]:
a = np.array([2.1,3.2,4.3])
print(a)

[ 2.1  3.2  4.3]


In [8]:
a = np.zeros((3,4))
print(a)
b = np.ones(5)
print(b)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[ 1.  1.  1.  1.  1.]


- Creating sequences of numbers 
- use arange 
    - with floating point step size precision makes predicting number of items not possible generally
- use linspace for floating point numbers to split up range into a number of items

In [13]:
# from, max value (not inclusive), step size
print(np.arange(0, 10, 2.5))

# from, max value (inclusive), number of items to split into
print(np.linspace(0,2,9))

[ 0.   2.5  5.   7.5]
[ 0.    0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ]


### Reshaping Arrays

- Use reshape(new dimensions)
    - Changes the shape without changing the data
- To make it a single dimension use np.ravel(a)

### Arithmetic Operations

- Applied elementwise
- New array is created

In [25]:
a = np.array( [20,30,40,50] )
b = np.arange(4)

# applied elementwise
c = a - b
print(c)

# elementwise squaring 
print(a **2)

# comparison is elementwise
print(a < 25)

# * operator = elementwise multiplication not 
# matrix product (use .dot for matrix product)
A = np.array([[1,5],[3,4]])
B = np.array([[5,3],[2,6]])

print('Multiplication using * -', A * B)

# Not A.B not commutative with B.A
print('Matrix product -', B.dot(A))
print('Matrix product -', A.dot(B))


[20 29 38 47]
[ 400  900 1600 2500]
[ True False False False]
Multiplication using * - [[ 5 15]
 [ 6 24]]
Matrix product - [[14 37]
 [20 34]]
Matrix product - [[15 33]
 [23 33]]
